name: Update ETF Data

on:
  schedule:
    - cron: '10 7 * * 1-5'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: 파이썬 환경 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 패키지 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 데이터 업데이트 스크립트 실행 및 블로그 포스팅
        env: # GitHub Secrets에 저장된 구글 API 키들을 코드로 전달합니다.
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
          BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
          BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
          BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
        run: python update_data.py

      - name: 생성된 CSV 파일 깃허브에 자동 커밋 & 푸시
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add etf_data.csv minervini_rs_etf_list.html
          git commit -m "Auto-update ETF data & Blogger post" || exit 0
          git push